### PR TITLE
Fix bug where Basic app does not print anything

### LINKED ISSUE #59: I can't get connection with couchdb.
I could make run the Basic.scala example but it doesn't make anything it show me success when I run it with the console (SBT) and when I run it with eclipse but it doesn't show any connection error or something like that, So I tried to figure out what the cause of the problen, seeing the configuration but the configuration it's so easy it's very simillar a simple JDBC, so I made a little example with java and I could get connection with the data base and I saw that, because I put the debug level in debug and I verified the data base was created and the files.
# So I don't know if you have any idea of what's going on because it doesn't throw any exception.

> run-main com.ibm.couchdb.examples.Basic
> [info] scalastyle using config /home/fidelity/workspace_6/couchdb-scala-master/scalastyle-config.xml
> [info] Processed 22 file(s)
> [info] Found 0 errors
> [info] Found 0 warnings
> [info] Found 0 infos
> [info] Finished in 2 ms
> [success] created output: /home/fidelity/workspace_6/couchdb-scala-master/target
> [info] Running com.ibm.couchdb.examples.Basic 
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> [success] Total time: 1 s, completed 06-jun-2016 14:52:25

### PR DESCRIPTION
**Pull request by ermyas**
Fixes #59

### CODE REVIEW

**Comment by beloglazov** [comment]
When I run `sbt "run-main com.ibm.couchdb.examples.Basic"`, I still get `SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"`, and then it hangs. Does it work for you?

**Comment by beloglazov** [comment]
It does work now and prints results, do you know why it keeps hanging after that?

**Comment by ermyas** [comment]
Hmm, I think it's because the http4s [pooled client](https://github.com/beloglazov/couchdb-scala/blob/master/src/main/scala/com/ibm/couchdb/core/Client.scala#L37) needs to be explicitly [shutdown ](https://github.com/http4s/http4s/blob/master/blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala#L51) , since it creates non daemon threads. 
What are your thoughts on how we can cleanly expose the http client's shutdown functionality in our API?

In the meantime, changing to use `unsafePerformSyncAttempt` and adding `System.exit(0)` at the end ...

**Comment by beloglazov** [comment]
`System.exit(0)` throws `sbt.TrapExitSecurityException`. How about replacing that with `couch.client.client.shutdownNow()` for now? We can also add a `shutdown` method to CouchDb that returns a `Task[Unit]` that calls `shutdownNow` internally.

**Comment by ermyas** [comment]
interesting, I don't get that exception. 

> How about replacing that with `couch.client.client.shutdownNow()` ...

does not look great :-) but will have to do for now I guess

**Comment by beloglazov** [comment]
It's working fine now, thanks! LGTM

It doesn't look great, I agree. We should add something nicer :)

**Pull request merged**
